/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3e484f',
        'primary-fixed': '#c4e7ff',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed-dim': '#7bd1fa',
        'surface-bright': '#f7f9fb',
        'surface-container': '#eceef0',
        'on-tertiary-fixed': '#001e2b',
        'surface-dim': '#d8dadc',
        'outline-variant': '#bdc8d1',
        'on-background': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'inverse-surface': '#2d3133',
        'on-tertiary-container': '#004961',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#001e2c',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-primary-container': '#004965',
        'tertiary-fixed': '#c0e8ff',
        'on-secondary-container': '#5c647a',
        'tertiary-container': '#64bbe3',
        'surface-container-high': '#e6e8ea',
        'surface-tint': '#00668a',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'secondary-container': '#dae2fd',
        'secondary-fixed': '#dae2fd',
        background: '#f8fafc',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#131b2e',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#004d66',
        outline: '#6e7980',
        'on-secondary-fixed-variant': '#3f465c',
        'on-primary-fixed-variant': '#004c69',
        error: '#ba1a1a',
        tertiary: '#006686',
        'primary-container': '#38bdf8',
        primary: '#00668a',
        'on-primary': '#ffffff',
        secondary: '#565e74',
        'inverse-primary': '#7bd0ff',
        surface: '#f8fafc',
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
